const nplPlayers = [
  { name: 'Sandeep Lamichhane', team: 'Biratnagar Kings', role: 'BOWL', credits: 10.5, nationality: 'Nepal' },
  { name: 'Basir Ahamad', team: 'Biratnagar Kings', role: 'AR', credits: 8.5, nationality: 'Nepal' },
  { name: 'Lokesh Bam', team: 'Biratnagar Kings', role: 'WK', credits: 8.5, nationality: 'Nepal' },
  { name: 'Subash Bhandari', team: 'Biratnagar Kings', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },
  { name: 'Naren Bhatta', team: 'Biratnagar Kings', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Marchant de Lange', team: 'Biratnagar Kings', role: 'BOWL', credits: 9.5, nationality: 'Foreign' },
  { name: 'Faf du Plessis', team: 'Biratnagar Kings', role: 'BAT', credits: 10.5, nationality: 'Foreign' },
  { name: 'Martin Guptill', team: 'Biratnagar Kings', role: 'BAT', credits: 9.5, nationality: 'Foreign' },
  { name: 'Pratish GC', team: 'Biratnagar Kings', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Sam Heazlett', team: 'Biratnagar Kings', role: 'BAT', credits: 9.0, nationality: 'Foreign' },
  { name: 'Narayan Joshi', team: 'Biratnagar Kings', role: 'AR', credits: 8.0, nationality: 'Nepal' },
  { name: 'Shrawan Kisku', team: 'Biratnagar Kings', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },
  { name: 'George Munsey', team: 'Biratnagar Kings', role: 'BAT', credits: 9.5, nationality: 'Foreign' },
  { name: 'Ayush Neupane', team: 'Biratnagar Kings', role: 'BAT', credits: 6.5, nationality: 'Nepal' },
  { name: 'Sahil Patel', team: 'Biratnagar Kings', role: 'WK', credits: 6.5, nationality: 'Nepal' },
  { name: 'Shankar Rana', team: 'Biratnagar Kings', role: 'BAT', credits: 7.5, nationality: 'Nepal' },
  { name: 'Shubham Ranjane', team: 'Biratnagar Kings', role: 'BAT', credits: 8.5, nationality: 'Foreign' },
  { name: 'Surya Tamang', team: 'Biratnagar Kings', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },

  // Chitwan Rhinos
  { name: 'Kushal Malla', team: 'Chitwan Rhinos', role: 'AR', credits: 9.5, nationality: 'Nepal' },
  { name: 'Bipin Acharya', team: 'Chitwan Rhinos', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Kamal Singh Airee', team: 'Chitwan Rhinos', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Deepak Bohara', team: 'Chitwan Rhinos', role: 'BAT', credits: 7.5, nationality: 'Nepal' },
  { name: 'Ravi Bopara', team: 'Chitwan Rhinos', role: 'AR', credits: 9.5, nationality: 'Foreign' },
  { name: 'Rijan Dhakal', team: 'Chitwan Rhinos', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Saugat Dhakal', team: 'Chitwan Rhinos', role: 'BOWL', credits: 6.5, nationality: 'Nepal' },
  { name: 'Gautam KC', team: 'Chitwan Rhinos', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },
  { name: 'Dev Khanal', team: 'Chitwan Rhinos', role: 'BAT', credits: 8.5, nationality: 'Nepal' },
  { name: 'Ranjeet Kumar', team: 'Chitwan Rhinos', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },
  { name: 'Dawid Malan', team: 'Chitwan Rhinos', role: 'BAT', credits: 10.0, nationality: 'Foreign' },
  { name: 'Alpesh Ramjani', team: 'Chitwan Rhinos', role: 'AR', credits: 8.5, nationality: 'Nepal' },
  { name: 'Amar Rautela', team: 'Chitwan Rhinos', role: 'AR', credits: 7.0, nationality: 'Nepal' },
  { name: 'Bipin Rawal', team: 'Chitwan Rhinos', role: 'WK', credits: 6.5, nationality: 'Nepal' },
  { name: 'Arjun Saud', team: 'Chitwan Rhinos', role: 'WK', credits: 8.0, nationality: 'Nepal' },
  { name: 'Sohail Tanvir', team: 'Chitwan Rhinos', role: 'BOWL', credits: 9.5, nationality: 'Foreign' },
  { name: 'Saif Zaib', team: 'Chitwan Rhinos', role: 'AR', credits: 9.5, nationality: 'Foreign' },

  // Janakpur Bolts
  { name: 'Anil Sah', team: 'Janakpur Bolts', role: 'WK', credits: 9.0, nationality: 'Nepal' },
  { name: 'Bikash Aagri', team: 'Janakpur Bolts', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },
  { name: 'Sachin Bhatta', team: 'Janakpur Bolts', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },
  { name: 'Sangeeth Cooray', team: 'Janakpur Bolts', role: 'BAT', credits: 8.5, nationality: 'Foreign' },
  { name: 'Shubh Kansakar', team: 'Janakpur Bolts', role: 'BAT', credits: 8.0, nationality: 'Nepal' },
  { name: 'Sanjay Krishnamurthi', team: 'Janakpur Bolts', role: 'BAT', credits: 8.5, nationality: 'Foreign' },
  { name: 'Nicol Loftie-Eaton', team: 'Janakpur Bolts', role: 'AR', credits: 9.0, nationality: 'Foreign' },
  { name: 'Aaditya Mahata', team: 'Janakpur Bolts', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },
  { name: 'Kishore Mahato', team: 'Janakpur Bolts', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Lahiru Milantha', team: 'Janakpur Bolts', role: 'WK', credits: 9.5, nationality: 'Foreign' },
  { name: 'Wayne Parnell', team: 'Janakpur Bolts', role: 'BOWL', credits: 10, nationality: 'Foreign' },
  { name: 'Lalit Rajbanshi', team: 'Janakpur Bolts', role: 'BOWL', credits: 9.5, nationality: 'Nepal' },
  { name: 'Lahiru Samarakoon', team: 'Janakpur Bolts', role: 'AR', credits: 8.5, nationality: 'Foreign' },
  { name: 'Aasif Sheikh', team: 'Janakpur Bolts', role: 'WK', credits: 9.5, nationality: 'Nepal' },
  { name: 'Rupesh Singh', team: 'Janakpur Bolts', role: 'AR', credits: 8.5, nationality: 'Nepal' },
  { name: 'Imran Tahir', team: 'Janakpur Bolts', role: 'BOWL', credits: 10.0, nationality: 'Foreign' },
  { name: 'Tul Bahadur Thapa', team: 'Janakpur Bolts', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },
  { name: 'Mayan Yadav', team: 'Janakpur Bolts', role: 'BAT', credits: 7.5, nationality: 'Nepal' },
  { name: 'Pappu Yadav', team: 'Janakpur Bolts', role: 'BOWL', credits: 6.5, nationality: 'Nepal' },

  // Karnali Yaks
  { name: 'Sompal Kami', team: 'Karnali Yaks', role: 'BOWL', credits: 10.0, nationality: 'Nepal' },
  { name: 'Will Bosisto', team: 'Karnali Yaks', role: 'AR', credits: 9.5, nationality: 'Foreign' },
  { name: 'Deepak Dumre', team: 'Karnali Yaks', role: 'WK', credits: 7.5, nationality: 'Nepal' },
  { name: 'Arjun Gharti', team: 'Karnali Yaks', role: 'WK', credits: 8.0, nationality: 'Nepal' },
  { name: 'Gulshan Jha', team: 'Karnali Yaks', role: 'AR', credits: 9.5, nationality: 'Nepal' },
  { name: 'Yuvraj Khatri', team: 'Karnali Yaks', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Jaykishan Kolsawala', team: 'Karnali Yaks', role: 'WK', credits: 8.0, nationality: 'Foreign' },
  { name: 'Max O\'Dowd', team: 'Karnali Yaks', role: 'BAT', credits: 9.0, nationality: 'Foreign' },
  { name: 'Priyank Panchal', team: 'Karnali Yaks', role: 'BAT', credits: 9.0, nationality: 'Foreign' },
  { name: 'Dipendra Rawat', team: 'Karnali Yaks', role: 'AR', credits: 7.5, nationality: 'Nepal' },
  { name: 'Pawan Sarraf', team: 'Karnali Yaks', role: 'AR', credits: 9.0, nationality: 'Nepal' },
  { name: 'Bipin Sharma', team: 'Karnali Yaks', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Imran Sheikh', team: 'Karnali Yaks', role: 'BAT', credits: 7.5, nationality: 'Nepal' },
  { name: 'Unish Thakuri', team: 'Karnali Yaks', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },
  { name: 'Mark Watt', team: 'Karnali Yaks', role: 'BOWL', credits: 9.0, nationality: 'Foreign' },
  { name: 'Nandan Yadav', team: 'Karnali Yaks', role: 'BOWL', credits: 9.0, nationality: 'Nepal' },
  { name: 'Najibullah Zadran', team: 'Karnali Yaks', role: 'BAT', credits: 9.0, nationality: 'Foreign' },

  // Kathmandu Gurkhas
  { name: 'Karan KC', team: 'Kathmandu Gurkhas', role: 'BOWL', credits: 9.5, nationality: 'Nepal' },
  { name: 'Mohammad Aadil Alam', team: 'Kathmandu Gurkhas', role: 'AR', credits: 9.0, nationality: 'Nepal' },
  { name: 'Shahab Alam', team: 'Kathmandu Gurkhas', role: 'BOWL', credits: 9.0, nationality: 'Nepal' },
  { name: 'Ben Charlesworth', team: 'Kathmandu Gurkhas', role: 'AR', credits: 9.0, nationality: 'Foreign' },
  { name: 'Gerhard Erasmus', team: 'Kathmandu Gurkhas', role: 'AR', credits: 9.5, nationality: 'Foreign' },
  { name: 'Dipesh Kandel', team: 'Kathmandu Gurkhas', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Milind Kumar', team: 'Kathmandu Gurkhas', role: 'BAT', credits: 9.5, nationality: 'Foreign' },
  { name: 'Rashid Khan', team: 'Kathmandu Gurkhas', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Uttam Magar', team: 'Kathmandu Gurkhas', role: 'WK', credits: 7.5, nationality: 'Nepal' },
  { name: 'Sunny Patel', team: 'Kathmandu Gurkhas', role: 'AR', credits: 8.5, nationality: 'Foreign' },
  { name: 'Sonu Devkota', team: 'Kathmandu Gurkhas', role: 'AR', credits: 7.0, nationality: 'Nepal' },
  { name: 'Bhim Sharki', team: 'Kathmandu Gurkhas', role: 'BAT', credits: 8.5, nationality: 'Nepal' },
  { name: 'John Simpson', team: 'Kathmandu Gurkhas', role: 'WK', credits: 9.0, nationality: 'Foreign' },
  { name: 'Pratik Shrestha', team: 'Kathmandu Gurkhas', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Aakash Tripathi', team: 'Kathmandu Gurkhas', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Tul B Thapa', team: 'Kathmandu Gurkhas', role: 'AR', credits: 7.5, nationality: 'Nepal' },
  { name: 'Ricardo Vasconcelos', team: 'Kathmandu Gurkhas', role: 'WK', credits: 9.0, nationality: 'Foreign' },
  { name: 'Santosh Yadav', team: 'Kathmandu Gurkhas', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },

  // Lumbini Lions
  { name: 'Rohit Paudel', team: 'Lumbini Lions', role: 'BAT', credits: 9.5, nationality: 'Nepal' },
  { name: 'Dinesh Adhikari', team: 'Lumbini Lions', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Sameer Ali', team: 'Lumbini Lions', role: 'BAT', credits: 6.5, nationality: 'Nepal' },
  { name: 'Tilak Bhandari', team: 'Lumbini Lions', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Thomas Draca', team: 'Lumbini Lions', role: 'BOWL', credits: 8.0, nationality: 'Foreign' },
  { name: 'Abhishesh Gautam', team: 'Lumbini Lions', role: 'BOWL', credits: 7.5, nationality: 'Nepal' },
  { name: 'Durgesh Gupta', team: 'Lumbini Lions', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Aadil Khan', team: 'Lumbini Lions', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Sher Malla', team: 'Lumbini Lions', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Gulbadin Naib', team: 'Lumbini Lions', role: 'AR', credits: 10.0, nationality: 'Foreign' },
  { name: 'Dilip Nath', team: 'Lumbini Lions', role: 'WK', credits: 8.0, nationality: 'Nepal' },
  { name: 'Bishal Patel', team: 'Lumbini Lions', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'D\'Arcy Short', team: 'Lumbini Lions', role: 'BAT', credits: 9.5, nationality: 'Foreign' },
  { name: 'Sundeep Jora', team: 'Lumbini Lions', role: 'BAT', credits: 9.0, nationality: 'Nepal' },
  { name: 'JJ Smit', team: 'Lumbini Lions', role: 'AR', credits: 8.5, nationality: 'Foreign' },
  { name: 'Ruben Trumpelmann', team: 'Lumbini Lions', role: 'BOWL', credits: 9.0, nationality: 'Foreign' },

  // Pokhara Avengers
  { name: 'Kushal Bhurtel', team: 'Pokhara Avengers', role: 'BAT', credits: 9.5, nationality: 'Nepal' },
  { name: 'Aakash Chand', team: 'Pokhara Avengers', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Rohit Chand', team: 'Pokhara Avengers', role: 'BAT', credits: 6.5, nationality: 'Nepal' },
  { name: 'Sandeep Chhetri', team: 'Pokhara Avengers', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Trit Raj Das', team: 'Pokhara Avengers', role: 'BAT', credits: 8.0, nationality: 'Nepal' },
  { name: 'Dan Douthwaite', team: 'Pokhara Avengers', role: 'AR', credits: 8.0, nationality: 'Foreign' },
  { name: 'Sagar Dhakal', team: 'Pokhara Avengers', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Dinesh Kharel', team: 'Pokhara Avengers', role: 'BAT', credits: 7.5, nationality: 'Nepal' },
  { name: 'Bipin Khatri', team: 'Pokhara Avengers', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Arjun Kumal', team: 'Pokhara Avengers', role: 'WK', credits: 7.5, nationality: 'Nepal' },
  { name: 'James Neesham', team: 'Pokhara Avengers', role: 'AR', credits: 10.0, nationality: 'Foreign' },
  { name: 'Krishna Poudel', team: 'Pokhara Avengers', role: 'BOWL', credits: 6.5, nationality: 'Nepal' },
  { name: 'Raymon Reifer', team: 'Pokhara Avengers', role: 'AR', credits: 9.0, nationality: 'Foreign' },
  { name: 'Adam Rossington', team: 'Pokhara Avengers', role: 'WK', credits: 9.0, nationality: 'Foreign' },
  { name: 'Jason Roy', team: 'Pokhara Avengers', role: 'BAT', credits: 10.0, nationality: 'Foreign' },
  { name: 'Kiran Thagunna', team: 'Pokhara Avengers', role: 'BAT', credits: 8.0, nationality: 'Nepal' },
  { name: 'Abhisekh Tiwari', team: 'Pokhara Avengers', role: 'BOWL', credits: 7.0, nationality: 'Nepal' },

  // Sudur Paschim Royals
  { name: 'Dipendra Singh Airee', team: 'Sudur Paschim Royals', role: 'AR', credits: 10.5, nationality: 'Nepal' },
  { name: 'Binod Bhandari', team: 'Sudur Paschim Royals', role: 'WK', credits: 8.5, nationality: 'Nepal' },
  { name: 'Abinash Bohara', team: 'Sudur Paschim Royals', role: 'BOWL', credits: 8.5, nationality: 'Nepal' },
  { name: 'Dipak Bohara', team: 'Sudur Paschim Royals', role: 'WK', credits: 7.0, nationality: 'Nepal' },
  { name: 'Milan Bohara', team: 'Sudur Paschim Royals', role: 'BAT', credits: 7.0, nationality: 'Nepal' },
  { name: 'Josh Brown', team: 'Sudur Paschim Royals', role: 'BAT', credits: 8.5, nationality: 'Foreign' },
  { name: 'Hemant Dhami', team: 'Sudur Paschim Royals', role: 'BOWL', credits: 8.0, nationality: 'Nepal' },
  { name: 'Hikmat Mahara', team: 'Sudur Paschim Royals', role: 'BOWL', credits: 6.5, nationality: 'Nepal' },
  { name: 'Ishan Pandey', team: 'Sudur Paschim Royals', role: 'BAT', credits: 8.0, nationality: 'Nepal' },
  { name: 'Tek Rawat', team: 'Sudur Paschim Royals', role: 'WK', credits: 6.5, nationality: 'Nepal' },
  { name: 'Naren Saud', team: 'Sudur Paschim Royals', role: 'AR', credits: 7.5, nationality: 'Nepal' },
  { name: 'Harmeet Singh', team: 'Sudur Paschim Royals', role: 'AR', credits: 9.0, nationality: 'Nepal' },
  { name: 'Aarif Sheikh', team: 'Sudur Paschim Royals', role: 'BAT', credits: 8.5, nationality: 'Nepal' },
  { name: 'Chris Lynn', team: 'Sudur Paschim Royals', role: 'BAT', credits: 10.5, nationality: 'Foreign' },
  { name: 'Scott Kuggeleijn', team: 'Sudur Paschim Royals', role: 'AR', credits: 9.5, nationality: 'Foreign' },
  { name: 'Dipendra Thapa', team: 'Sudur Paschim Royals', role: 'WK', credits: 7.0, nationality: 'Nepal' }
];